/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ermes.salario;

public final class R {
    public static final class array {
        public static final int categoriaList=0x7f050001;
        public static final int categoriaListValues=0x7f050002;
        public static final int hijosList=0x7f050003;
        public static final int laboralList=0x7f050004;
        public static final int laboralListValues=0x7f050005;
        public static final int nPagasList=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int euro=0x7f020000;
        public static final int hoja2=0x7f020001;
        public static final int ic_launcher=0x7f020002;
    }
    public static final class id {
        public static final int acerca=0x7f09000f;
        public static final int ajustes=0x7f09000e;
        public static final int btnCalcular=0x7f090004;
        public static final int lblPagaExtra=0x7f09000c;
        public static final int txt1=0x7f090000;
        public static final int txt2=0x7f090001;
        public static final int txt3=0x7f090002;
        public static final int txtAnual=0x7f090003;
        public static final int txtBaseIRPF=0x7f090008;
        public static final int txtDeduccionFamiliar=0x7f090009;
        public static final int txtDeduccionSS=0x7f090007;
        public static final int txtIRPF=0x7f090006;
        public static final int txtIRPFanual=0x7f09000a;
        public static final int txtNPagas=0x7f090005;
        public static final int txtNetoMensual=0x7f09000b;
        public static final int txtPagaExtra=0x7f09000d;
    }
    public static final class layout {
        public static final int acerca=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int opciones_menu=0x7f080000;
    }
    public static final class string {
        public static final int acerca1=0x7f060002;
        public static final int acerca2=0x7f060003;
        public static final int app_name=0x7f060001;
        /** Lista de categorias 
         */
        public static final int categoria1=0x7f060005;
        public static final int categoria2=0x7f060006;
        public static final int categoria3=0x7f060007;
        public static final int categoria4=0x7f060008;
        public static final int categoria5=0x7f060009;
        public static final int categoria6=0x7f06000a;
        public static final int categoria7=0x7f06000b;
        public static final int contacto=0x7f060004;
        public static final int laboral1=0x7f06000c;
        public static final int laboral2=0x7f06000d;
        public static final int laboral3=0x7f06000e;
        public static final int laboral4=0x7f06000f;
        public static final int nPagas=0x7f060000;
    }
    public static final class style {
        public static final int fuente=0x7f070000;
        public static final int fuente_derecha=0x7f070001;
    }
    public static final class xml {
        public static final int ajustes=0x7f040000;
    }
}
